#!/bin/bash

if [ $1 -gt $2 ]; then
	m=$1; n=$2
else
	m=$2; n=$1
fi

#Print M,N
#echo m = $m
#echo n = $n

#Loop
while [ $r -ne 0 ]; do
	r='expr $m % $n'
	m=$n
	n=$r
done

#Print result
echo "$n"

exit 0
